source 'https://supermarket.chef.io'

cookbook 'apt',             '~> 2.2'
cookbook 'bluepill',        '~> 2.3'
cookbook 'build-essential', '~> 2.0'
cookbook 'ohai',            '~> 2.0'
cookbook 'runit',           '~> 1.2'
cookbook 'yum-epel',        '~> 0.3'

